accountsApp/urls.py
from django.urls import path
from accountsApp import views
from django.contrib.auth import views as Views
from.forms import LoginForm

app_name = 'accountsApp'

urlpatterns = [
    path('register/', views.registerV, name='register'),
    path('login/', Views.LoginView.as_view(template_name='accountsApp/login.html',
        redirect_authenticated_user = True, authentication_form = LoginForm ) , name='login'),
    path('logout/', Views.LogoutView.as_view(template_name='accountsApp/logout.html', 
        next_page ='accountsApp:login') , name='logout'),
    ]

myApp/urls.py
from django.contrib import admin
from django.urls import path
from myApp import views

app_name = 'myApp'

urlpatterns = [
    path('', views.indexView , name='home'),
    path('details/<int:id>/', views.detailsView , name='details'),
    path('newPost/', views.newPostView , name='newPost'),
    path('updatePost/<int:id>/', views.updateView , name='updatePost'),
    path('deletePost/<int:id>/', views.deleteView , name='deletePost'),
    path('search/', views.searchview , name='search'),
]

mysiteProject/urls.py
from xml.etree.ElementInclude import include
from django.contrib import admin
from django.urls import path , include
from myApp import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myApp.urls')),
    path('accounts/', include('accountsApp.urls')),
]
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

accountsApp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete = models.CASCADE, related_name ='Profile')
    birthday = models.DateField()
    phonenumber = models.IntegerField()
    
    def __str__(self):
        return self.user.username

myApp/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class PostModel(models.Model):
    title = models.CharField(max_length=55)
    content = models.TextField()
    image = models.ImageField(upload_to='media/image/',null = True)
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    
    def __str__(self):
        return 'titre:{}'.format(self.title , self.content)

accountsApp/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from accountsApp.models import Profile



class LoginForm(AuthenticationForm):
    username= forms.CharField(label = 'Username', widget=forms.TextInput(attrs={'class': 'form-control'}))
    password= forms.CharField(label = 'Password' , widget=forms.PasswordInput(attrs={'class': 'form-control'})) 


class UserForm(UserCreationForm):
    username= forms.CharField(label = 'Username', widget=forms.TextInput(attrs={'class': 'form-control'}))
    email= forms.CharField(label = 'Email', widget=forms.EmailInput(attrs={'class': 'form-control'}))
    password1= forms.CharField(label = 'Password' , widget=forms.PasswordInput(attrs={'class': 'form-control'})) 
    password2= forms.CharField(label = 'Password' , widget=forms.PasswordInput(attrs={'class': 'form-control'})) 
    class Meta :
        model = User
        fields = ('username','email','password1','password2')

class ProfileForm(forms.ModelForm):
    birthday= forms.DateField(label = 'Birthday', widget=forms.DateInput(attrs={
        'class': 'form-control' , 'type': 'date'}
                ))
    phonenumber= forms.IntegerField(label = 'Phone Number', widget=forms.DateInput(attrs={
        'class': 'form-control' , 'type': 'number'}
                ))
    class Meta:
        model = Profile
        fields =('birthday', 'phonenumber')

myApp/forms.py
from dataclasses import field, fields
from django import forms
from .models import PostModel

class PostForm(forms.ModelForm):
    title= forms.CharField(label = 'Title', widget=forms.TextInput(attrs={'class': 'form-control'}))
    content= forms.CharField(label = 'content' , widget=forms.Textarea(attrs={'class': 'form-control'}))
    class Meta:
        model = PostModel
        exclude = ('user',)

accountsApp/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from accountsApp.forms import UserForm,ProfileForm


# Create your views here.
def registerV(request):
    if request.user.is_authenticated:
        return redirect('myApp:home')
    
    if request.method == 'POST':
        form = UserForm(request.POST)
        ProfileF =ProfileForm(request.POST)
        if form.is_valid() and ProfileF.is_valid():
            user=form.save(commit=False)
            Profile = ProfileF.save(commit=False)
            Profile.user = user 
            user.save()
            Profile.save()
            return redirect('myApp:home')
    else:
        form =UserForm()
        ProfileF =ProfileForm()
    context={'form': form , 'profile':ProfileF}
    
    return render(request, 'accountsApp/register.html', context)

myApp/views.py
from django.shortcuts import render , redirect
from django.http import HttpResponseRedirect
from django.template import loader
from .models import PostModel
from .forms import PostForm
from django.contrib.auth.decorators import login_required
from django.http import Http404
from django.db.models import Q
from django.core.paginator import Paginator

# Create your views here.
@login_required
def indexView(request):
    Posts = PostModel.objects.all().order_by('id')
    paginator = Paginator(Posts , 3)
    pageNb = request.GET.get('page')
    page_obj = paginator.get_page(pageNb)
    nb = Posts.count() 
    message = str(nb) + ' posts'
    if nb <2 :
        message = str(nb) + ' post'
    
    context = {'i' : page_obj , 'nb': nb, 'message': message}  
    
    return render( request,'myApp/home.html',  context)

@login_required
def detailsView(request , id):
    Posts = PostModel.objects.get(id=id)
    context = { 'i': Posts}
    return render(request , 'myApp/details.html', context)

@login_required
def newPostView(request):
    if request.method== 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            form = form.save(commit=False)
            form.user = request.user
            form.save()
            return redirect('myApp:home')
    else:
        form = PostForm()
    context ={'form': form}
    return render(request , 'myApp/newPost.html',context)

@login_required
def updateView(request,id):
    Post = PostModel.objects.get(id=id)
    if Post.user == request.user:
        if request.method == 'POST':
            form = PostForm(request.POST, request.FILES , instance = Post)
            if form.is_valid():
                form.save()
                return redirect('myApp:home')
        else:
            form = PostForm( instance= Post)
        
    else:
        raise Http404
    context = { 'post':Post, 'form':form}
    return render(request, 'myApp/update.html',context)

@login_required
def deleteView(request, id):
    Post = PostModel.objects.get(id=id)
    if Post.user == request.user:
        Post.delete()
    else:
        raise Http404
    return redirect('myApp:home')
    
    
@login_required
def searchview(request):
    search = request.GET.get('search')
    post = PostModel.objects.filter(Q(title__icontains= search)|Q(content__icontains= search)
                                    |Q(image__icontains= search))
    nb = post.count()
    message = str(nb) + ' '+ 'posts'
    if nb <2 :
        message = str(nb) + ' post'
    context = {'search': search, 'post':  post , 'message': message}
    return render(request, 'myApp/search.html', context)

accountsApp/templates/accountsApp/login.html
{% extends 'layouts/base.html' %}
{% block title %}
    login
{% endblock %}
{% block content %}
<h1>Login</h1>

    <div class = "container">
        <div class = "row">
            <div class = "col-md-8 mx-auto">
                <form action="" method="POST" enctype="multipart/form-data">
                {% for field in form %}
                    <div class="form-group">
                    {% csrf_token %}
                    <strong>{{ field.label_tag }}</strong>
                    <div class = 'container'>{{ field }}</div>
                    {% if field.help_text %}
                    <p class = "help">{{field.help_text}}</p>
                    {% endif %}
                    </div>
                {%  endfor %} 
                </br>
                <input type ="submit" class = "btn btn-primary" value = "login">
                </form>
            </div>
        </div>
    </div> 
{% endblock %}

accountsApp/templates/accountsApp/register.html
{% extends 'layouts/base.html' %}
{% block title %}
    register
{% endblock %}
{% block content %}
<h1>register</h1>
<div class = "container">
    <div class = "row">
        <div class = "col-md-8 mx-auto">
            <form action="" method="POST" enctype="multipart/form-data">
            {% for field in form %}
                <div class="form-group">
                {% csrf_token %}
                <strong>{{ field.label_tag }}</strong>
                <div class = 'container'>{{ field }}</div>
                {% if field.help_text %}
                <p class = "help">{{field.help_text}}</p>
                {% endif %}
                </div>
            {%  endfor %} 
            </br>
            {% for field in profile %}
                <div class="form-group">
                <strong>{{ field.label_tag }}</strong>
                <div class = 'container'>{{ field }}</div>
                {% if field.help_text %}
                <p class = "help">{{field.help_text}}</p>
                {% endif %}
                </div>
            {%  endfor %} 
            </br>
            <input type ="submit" class = "btn btn-primary" value = "Register">
            </form>
        </div>
    </div>
</div> 
{% endblock %}

myApp/templates/myApp/details.html
{% extends 'layouts/base.html' %} 
{% block title %}
details 
{% endblock %}

{% block content %}
<h1>Details</h1>
<div>
<h1>{{i.id}}   {{i.title}}</h1>
<p>{{i.content}}</P>
</div>
{% endblock %}

myApp/templates/myApp/home.html
{% extends 'myApp/layouts/base.html' %}
{% load static %}
{% load static %}
{% block title %}
All posts 
{% endblock %}


{% block content %}

<h1>home page</h1>
<h4 class= 'text-center'>on a : {{ message }}</h4>
{% comment %} <img src="{% static 'image/fruit.jpg' %}" {% endcomment %}
<div class="row  row-cols-md-3  row-cols-sm-2">
{% for i in i %}
<div class = "col">
    <div class ="card mb-3 shadow"   >
        <div class="card-body style="width: 18rem;">
            {% if i.image %}
            <img src="{{ i.image.url }}" class="card-img-top" alt="...">
            {% endif %}
            <h5 class="card-title">{{i.title}}</h5>
            <p class="card-text">{{ i.content|truncatechars:"100" }}</p>
            <a href="{% url 'myApp:details' i.id %}" class="btn btn-primary">More</a>
            {% if i.user == request.user %}
            <a href="{% url 'myApp:updatePost' i.id %}" class="btn btn-success">Update</a>
            <a href="{% url 'myApp:deletePost' i.id %}" class="btn btn-danger">Delete</a>
            {% endif %}
            
        </div>
        <div class = 'card-footer'>
            {{ i.user.username }}
        </div>
    </div>
</div>
{% endfor %}
</div>
<nav >
    <ul class="pagination justify-content-center">
        {% if i.has_previous %}
        <li class="page-item ">
            <a class="page-link" href="?page={{ i.previous_page_number }}">
                <span aria-hidden = true>&laquo; Previous</span>
            </a>
        </li>
        {% endif %}
        <li class= "page-item">
            <p class= "page-link text-muted">
            {{ i.number }} of {{ i.paginator.num_pages }}.
            </p>
        </li>
        {% if i.has_next %}
        <li class="page-item ">
            <a class="page-link" href="?page={{ i.next_page_number }}">
                <span aria-hidden = true>&raquo; Next</span>
            </a>
        </li>
        {% endif %}
    </ul>
</nav>
{% endblock %}

myApp/templates/myApp/layouts/base.html
{% extends 'layouts/base.html' %}
{% load static %}
{% load static %}

{% block stylesheet %}
<link rel="stylesheet" href ="{% static 'css/styles.css'  %} ">

{% endblock stylesheet %}

{% block javaScript%}
    
    <script  src="{% static 'js/app.js' %}"> </script>        
{% endblock %}

myApp/templates/myApp/newPost.html
{% extends 'layouts/base.html' %}
{% block title %}
    new Post 
{% endblock %}
{% block content %}
<h1>new post</h1>

    <div class = "container">
        <div class = "row">
            <div class = "col-md-8 mx-auto">
                <form action="" method="POST" enctype="multipart/form-data">
                {% for field in form %}
                    <div class="form-group">
                    {% csrf_token %}
                    <strong>{{ field.label_tag }}</strong>
                    <div class = 'container'>{{ field }}</div>
                    {% if field.help_text %}
                    <p class = "help">{{field.help_text}}</p>
                    {% endif %}
                    </div>
                {%  endfor %} 
                </br>
                <input type ="submit" class = "btn btn-primary" value = "Create new post">
                </form>
            </div>
        </div>
    </div> 
{% endblock %}

myApp/templates/myApp/search.html
{% extends 'myApp/layouts/base.html' %}
{% load static %}
{% block title %}
    search
{% endblock %}


{% block content %}

    <h3 class = "text-center">Results: {{ message }} </h3>
<div class="row  row-cols-md-3  row-cols-sm-2">
    {% for post in post %}
<div class = "col">
    <div class ="card mb-3 shadow"   >
        <div class="card-body style="width: 18rem;">
            {% if post.image %}
            <img src="{{ post.image.url }}" class="card-img-top" alt="...">
            {% endif %}
            <h5 class="card-title">{{post.title}}</h5>
            <p class="card-text">{{ post.content|truncatechars:"100" }}</p>
            <a href="{% url 'myApp:details' post.id %}" class="btn btn-primary">More</a>
            {% if i.user == request.user %}
            <a href="{% url 'myApp:updatePost' post.id %}" class="btn btn-success">Update</a>
            <a href="{% url 'myApp:deletePost' post.id %}" class="btn btn-danger">Delete</a>
            {% endif %}
            
        </div>
        <div class = 'card-footer'>
            {{ post.user.username }}
        </div>
    </div>
</div>
{% endfor %}
</div>

{% endblock %}

myApp/templates/myApp/update.html
{% extends 'myApp/layouts/base.html' %}
{% load static %}
{% block title %}
    Update
{% endblock %}


{% block content %}

<h1>Update page  {{post}}</h1>

<div class = "container">
    <div class = "row">
        <div class = "col-md-8 mx-auto">
            <form action="" method="POST" enctype="multipart/form-data">
            {% for field in form %}
                <div class="form-group">
                {% csrf_token %}
                <strong>{{ field.label_tag }}</strong>
                {{ field }}
                {% if field.help_text %}
                <p class = "help">{{field.help_text}}</p>
                {% endif %}
                </div>
                
            {%  endfor %} 
            <img class =' mb-3 mt-3'src="{{ post.image.url }}" width =" 200"></br>
            </br>
            <input type ="submit" class = "btn btn-primary" value = "Update Post">
            </form>
        </div>
    </div>
</div> 


{% endblock %}

templates/index.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body>
        <h1>welcome to my app 7/02/2023</h1>
        {% for i in materielInfo %}
        {{ i }}<br>

        {% endfor%}
        <script src="" async defer></script>
    </body>
</html>

templates/layouts/base.html
{% load static %}
<!DOCTYPE html>

<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>{% block title %}{{mysSite}}/{% endblock %}</title> 
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href ="{% static 'css/bootstrap.css'  %} ">
        {% block stylesheet %}
        
        {% endblock stylesheet %}
    </head>
        <body>
            <heder>
                {% block header %}
                {% include 'layouts/nav.html'%}
                {% endblock %}
            </header>
            <div class="container">
            {% block content %}
                
            {% endblock %}
            </div>
            
            <script src="{% static 'js/bootstrap.bundle.min.js'%}"></script>
            {% block javaScript%}
            
            {% endblock %}
        </body>
</html>

templates/layouts/nav.html
<nav class="navbar navbar-expand-lg navbar-light bg-light mb-4 shadow-lg">
    <div class="container">
      <a class="navbar-brand" href="{% url 'myApp:home'%}">My Blog</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#SupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="SupportedContent">
        <ul class="navbar-nav ms-auto ">
          {% if request.user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link " aria-current="page" href="{% url 'myApp:home'%}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'myApp:newPost'%}">new Post</a>
          </li>
          <li class="nav-item">
            <a class="nav-link " href="{% url 'accountsApp:logout'%}">logout</a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link " href="{% url 'accountsApp:logout'%}">login</a>
          </li>
          <li class="nav-item">
            <a class="nav-link " href="{% url 'accountsApp:register'%}">sign up</a>
          </li>
          {% endif %}
          
        </ul>
        
      </div>
      <form action = "{% url 'myApp:search' %}" class="d-flex m-lg-3" method = "GET">
        <input placeholder = 'recherche' class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name ="search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>

    </div>
  </nav>